### ISSUE TITLE
Can not connect to Q03UDECPU

### ISSUE THREAD

**Issue by jp5525** [Steve-Mcl/node-red-contrib-mcprotocol#5]
Hello,

Im trying connect to a Mitsubishi Q03UDECPU on a Q38DB Rack Base. Unfortunately when ever i try and connect to it i receive this error and was hoping someone might be able to provide me with any insight 

TypeError : Cannot read property 'console' of undefined

Thanks

**Comment by Steve-Mcl** [comment]
That is quite strange. 

What are you running node-red on? 

What version of nodejs & node-red are you running?

Can you copy & paste node-red logs (or copy terminal output if running from command line).

**Comment by jp5525** [comment]
Yes 

Im running windows 10, with node v12.8.1 and node red v1.0.0

Here are the node red logs
```
Welcome to Node-RED
===================

 

26 Jan 12:24:19 - [info] Node-RED version: v1.0.0
26 Jan 12:24:19 - [info] Node.js  version: v12.8.1
26 Jan 12:24:19 - [info] Windows_NT 10.0.15063 x64 LE
26 Jan 12:24:20 - [info] Loading palette nodes
26 Jan 12:24:21 - [info] Worldmap version 2.4.1
26 Jan 12:24:21 - [info] Dashboard version 2.23.0 started at /ui
26 Jan 12:24:22 - [info] Context store  : 'default' [module=memory]
26 Jan 12:24:22 - [info] User directory : C:\Users\SystemMIS/.mfgx-edge/server-50000
26 Jan 12:24:22 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
26 Jan 12:24:22 - [info] Flows file     : C:\Users\SystemMIS\.mfgx-edge\server-50000\flows.json
26 Jan 12:24:22 - [warn] 

 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

 

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

 

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

 

26 Jan 12:24:22 - [info] Starting flows
26 Jan 12:24:22 - [error] [MC Read:7c0f619a.c6e4b] TypeError: Cannot read property 'console' of undefined
    at new mcRead (C:\Users\SystemMIS\.mfgx-edge\server-50000\node_modules\node-red-contrib-mcprotocol\nodes\read.js:40:42)
    at Object.createNode (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\Flow.js:189:48)
    at start (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\index.js:329:33)
    at tryCatchReject (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\makePromise.js:804:4)
    at Fulfilled.when (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\makePromise.js:592:4)
    at Pending.run (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\Scheduler.js:27:9)
26 Jan 12:24:22 - [error] [MC Read:4e3d49b6.096058] TypeError: Cannot read property 'console' of undefined
    at new mcRead (C:\Users\SystemMIS\.mfgx-edge\server-50000\node_modules\node-red-contrib-mcprotocol\nodes\read.js:40:42)
    at Object.createNode (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\Flow.js:189:48)
    at start (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\index.js:329:33)
    at tryCatchReject (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\makePromise.js:804:4)
    at Fulfilled.when (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\makePromise.js:592:4)
    at Pending.run (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\when\lib\Scheduler.js:27:9)
26 Jan 12:24:22 - [info] Started flows
26 Jan 12:24:22 - [info] [udp out:3fb7e243.7ec28e] udp ready: :
26 Jan 12:25:00 - [info] Stopping flows
26 Jan 12:25:00 - [info] [udp out:3fb7e243.7ec28e] udp output stopped
26 Jan 12:25:00 - [info] Stopped flows
26 Jan 12:25:00 - [info] Starting flows
26 Jan 12:25:00 - [error] [MC Read:7c0f619a.c6e4b] TypeError: Cannot read property 'console' of undefined
    at new mcRead (C:\Users\SystemMIS\.mfgx-edge\server-50000\node_modules\node-red-contrib-mcprotocol\nodes\read.js:40:42)
    at Object.createNode (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\Flow.js:189:48)
    at start (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\index.js:329:33)
    at c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\index.js:196:21
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
26 Jan 12:25:00 - [error] [MC Read:4e3d49b6.096058] TypeError: Cannot read property 'console' of undefined
    at new mcRead (C:\Users\SystemMIS\.mfgx-edge\server-50000\node_modules\node-red-contrib-mcprotocol\nodes\read.js:40:42)
    at Object.createNode (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\Flow.js:189:48)
    at start (c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\index.js:329:33)
    at c:\Program Files (x86)\MFGx Edge\resources\app.asar\node_modules\@node-red\runtime\lib\nodes\flows\index.js:196:21
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
26 Jan 12:25:00 - [info] Started flows
26 Jan 12:25:00 - [info] [udp out:3fb7e243.7ec28e] udp ready: :

**Comment by Steve-Mcl** [comment]
Looking at your log, I spotted `mfgx-edge\server-50000` and searched the net for it and found https://www.mfgxonline.com/Capabilities/edge-platform 

It looks like this company using node-red inside their product (within a windows application?) and it is quite an old version (V1.0.0).


According to your post, it is failing on [this line](https://github.com/Steve-Mcl/node-red-contrib-mcprotocol/blob/22780b36d76db7d03fc88bd0c87bdd0e1e552b72/nodes/read.js#L40) in particular `RED.settings.logging.console.level`

So without digging too deep, was property was probably added after V1.0.0

Is it possible to upgrade the version of node-red? (V1.0.0 is quite old now)

PS: Why are you using this MFGx platform for node-red? 
Can you not install node-red directly without all the stuff MFGx provides?  Will a normal install of node-red not integrate with their platform?

**Comment by jp5525** [comment]
Node red can partially integrate with MFGx. There have nodes for it, but some of the features need to have the app installed, like using mfgx user accounts for access control on the editor.

We were actually able to get it working by adding this to the settings file
``` 
logging: {
    console: {
        level: "info",
        metrics: false,
        audit: false
    }
}
